### ISSUE TITLE
Product Catalog Menu Displays 'Loading...' When the Catalog is Empty

### ISSUE THREAD

**Issue by PatrickCVest** [todd-buck/CapstoneProject#6]
The catalog menu might should, instead, display an empty table when the catalog is empty.

**Comment by todd-buck** [comment]
What is the desired behavior when attempting to display an empty database? The only way that I currently have to display data columns requires at least one item to be in the database.

**Comment by PatrickCVest** [comment]
> What is the desired behavior when attempting to display an empty database? The only way that I currently have to display data columns requires at least one item to be in the database.

Could this be adjusted to just display an empty table?

**Comment by todd-buck** [comment]
Without an API endpoint to get table schema, no. This was discussed in one of our previous conversations, and it was my understanding that such an API endpoint would not be created. If this has changed or you have other ideas for implementation, we can discuss.

**Comment by todd-buck** [comment]
Please reach out once the API endpoint previously discussed has been implemented.

**Comment by PatrickCVest** [comment]
Fixed by hard-coding catalog columns (pending later enhancement from schema API) and displaying empty table when error code is thrown from back-end.
